### ISSUE TITLE
No hover responses on dhall-haskell in windows

### ISSUE THREAD

**Issue by fendor** [mpickering/haskell-ide-engine#32]
> Hi, i've experienced some hangs testing this pr within dhall-haskell project:
> 
> * Opening the project with vscode and hie master works (not with all files but it does with ./dhall/src/Dhall.hs)
> * When using this branch the load of cradle finishes but hover on any term (or any other action involving hie) is unreponsive: the log is [here](https://gist.github.com/jneira/65c0ae7359beeb066c0d6174bc700bc1#file-hie-log) (including the hover request and the cancellation)
> * Testing hie-bios on the project without explicit hie.yaml works: see https://gist.github.com/jneira/65c0ae7359beeb066c0d6174bc700bc1#file-cradle-output

_Originally posted by @jneira in https://github.com/haskell/haskell-ide-engine/pull/1126#issuecomment-539237025_

cc @jneira

**Comment by mpickering** [comment]
Did you test this yourself @fendor?

**Comment by fendor** [comment]
Yes, but I can not reproduce.
Cloning `dhall-haskell` with hie.yaml
```yaml
cradle: 
  stack:
```

 works for me.

**Comment by jneira** [comment]
Maybe it is a specific behaviour in windows, i've experienced it in win 7 and 10, with both the `hie-bios` and the `cabal-helper-helper` branches, using an explicit cradle like fendor's one and without it .

It works in simple stack projects, though.

**Comment by jneira** [comment]
I've tried the last `cabal-helper-helper` branch version (reverting haskell-lsp-0.16 to enable code actions) and hover is responsive again, including quick fixes. I guess the main `hie-bios` branch will work too. Without reverting it hte hover is responsive too (but with no quick fixes)
I've tested the "Replace with" quick fix and it delete the unknown term instead replacing it with the proposal... but this is another story
So maybe we could close this one.

**Comment by jneira** [comment]
I've setup a simple cabal/stack multipackage project: https://github.com/jneira/cabal-multi-test and i've done an extensive testing

TL;DR

* in all succesful cases there is a notificacion in vscode: "lintCmd: no access to the persisted file."
* hover unresponsive only when cradle init doesnt finish

------------------------------

* `cabal-helper-helper` branch with no explicit `hie.yaml`
  * With `stack.yaml` and *no* `cabal.project`: it chooses the `Cabal-Helper-Stack` cradle
    * It works setting the test suite name equal in both subpackages, the cradle initialization finishes
    * there is a notificacion in vscode: "lintCmd: no access to the persisted file."
    * Hover responds in all cases
    * Logs: https://gist.github.com/jneira/994301d33c2d28d50a3c5330f44132cb
  * With `stack.yaml` and `cabal.project`: it chooses the `Cabal-Helper-Cabal-V2` cradle
    * With the same test suite name: the cradle init doesn't finish
      * hover doesn't respond
      * log: https://gist.github.com/jneira/e08161485287c77998b31d9a01dc2ad1
    * With no duplicate test names in both packages the cradle init finishes.
      * there is a notificacion in vscode: "lintCmd: no access to the persisted file."
      * hover responds
      * logs: https://gist.github.com/jneira/b4e6fa867a2e78a1113d3d6cc1e7d56e
* `hie-bios` branch with no explicit `hie.yaml`
  * With `stack.yaml` *and* `cabal.project`: it chooses the `stack` cradle (note that the behaviour is the oppsite of the `cabal-helper-helper` branch)
    * Hover responds
    * there is a notificacion in vscode: "lintCmd: no access to the persisted file."
  * With *no* `stack.yaml` and `cabal.project`: it chooses the `cabal` cradle
    * It thows an error (expected?): 
```
CradleError (ExitFailure 1) "Failed to parse result of calling cabal\ncabal: No targets given and there is no package in the current directory. Use\nthe target 'all' for all packages in the project or specify packages or\ncomponents by name or location. See 'cabal build --help' for more details on\ntarget options.\n\n\n\n"
```
*  `hie-bios` branch with explicit `hie.yaml`, without `stack-yaml` and with the same test suite name in both subpackages:

```yaml
cradle:
  multi:
    - path: ./package1/
      config:
        cradle:
          cabal:
            component: "lib:package1"
    - path: ./package1/
      config:
        cradle:
          cabal:
            component: "package1:example-test" # test:example-test doesn't work
    - path: ./package1/
      config:
        cradle:
          cabal:
            component: "exe:package1"
    - path: ./package2/
      config:
        cradle:
          cabal:
            component: "lib:package2"
    - path: ./package2/
      config:
        cradle:
          cabal:
            component: "package2:example-test" # test:example-test doesn't work
    - path: ./package2/
      config:
        cradle:
          cabal:
            component: "exe:package1"

```
  * there is a notificacion in vscode: "lintCmd: no access to the persisted file."
  * It works as expected in all source files of all components
  * Hover responds

* the `cabal-helper-helper` branch trigger a build with stack or cabal (that can be lengthy), if that build fails the cradle initialization doesn't finish and hover doesnt responds (only `waiting`)
  * the question is if the builds are triggered from hie directly or from cabal-helper
